image: docker..vn/base-image/gitlab-ci-pipeline-php7.3
variables:
  GROUP_ID: ""
  COMPOSER_MEMORY_LIMIT: -1
  DEPLOY_NAME: "deploy-${GROUP_ID}-${CI_PROJECT_NAME}"
stages:
  - dockerize
  - deployk8s

before_script:
  - VERSION=$(grep "APP_VERSION" .env.production | cut -d "=" -f 2)
  - IMAGE_NAME=${DOCKER_REGISTRY_URL}/${GROUP_ID}/${CI_PROJECT_NAME}
  - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
      IMAGE_FULL=${IMAGE_NAME}:${VERSION};
      ENVIROMENT=production;
    fi
  - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then
      IMAGE_FULL=${IMAGE_NAME}:dev-${CI_COMMIT_REF_SLUG}-$CI_COMMIT_SHORT_SHA;
      ENVIROMENT=staging;
    fi

build image:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
  stage: dockerize
  image: docker..vn/base-image/docker-18.06.3:latest
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL
    - docker pull ${IMAGE_NAME}:latest || true
    - docker build -f Dockerfile -t ${IMAGE_FULL} -t ${IMAGE_NAME}:latest --build-arg APP_ENV=${ENVIROMENT} --build-arg APP_VERSION=${VERSION} --cache-from ${IMAGE_NAME}:latest .
    - docker push ${IMAGE_FULL}
    - docker push ${IMAGE_NAME}:latest
  only:
    refs:
      - pushes